### PR TITLE
[OF#5932] add confirmation email checkbox for profile component

### LINKED ISSUE #5932: Profile component should offer "use this email for confirmation"
### Product versie / Product version

3.4.0

### Customer reference

Laurens & Bregje

### Omschrijf het probleem / Describe the bug

Image

### Stappen om te reproduceren / Steps to reproduce

_No response_

### Verwacht gedrag / Expected behavior

_No response_

### Screen resolution

None

### Device

None

### OS

None

### Browser

_No response_

### PR DESCRIPTION
**Pull request by SonnyBA**
Frontend changes required for https://github.com/open-formulieren/open-forms/issues/5932. Requires https://github.com/open-formulieren/types/pull/87 for the updated component schema.

### CODE REVIEW

File: src/registry/customerProfile/edit.tsx
Comment (sergei-maertens) [inline src/registry/customerProfile/edit.tsx:1]: I'm missing the update in the types that defines the property on the `customerProfile` component, and the associated updated defaults on L113 :-)

**Review by sergei-maertens — CHANGES_REQUESTED** [review]

File: src/registry/customerProfile/edit.tsx
Comment (SonnyBA) [reply src/registry/customerProfile/edit.tsx:1]: See https://github.com/open-formulieren/types/pull/87 for the update to the component schema.

**Review by annashamray — COMMENTED** [review]
Looks good, let's wait for merging of types PR, I wonder if the profile tests in customerProfile/edit-validation.spec.ts still pass after the types are updated

Could you please link this PR with the issue?

**Comment by SonnyBA** [comment]
> Looks good, let's wait for merging of types PR, I wonder if the profile tests in customerProfile/edit-validation.spec.ts still pass after the types are updated
> 
> Could you please link this PR with the issue?

~~I added the new required `confirmationRecipient` property to various files (even though a new types release was not done yet), this will probably cause the builds to fail. This should be fixed by bumping the types version which includes the new property.~~

[Version 1.1.0](https://github.com/open-formulieren/types/releases/tag/1.1.0) was released for this.

File: src/components/ComponentConfiguration.stories.tsx [hunk 1]
```diff
@@ -3123,19 +3123,41 @@ export const Profile: Story = {
...
+      expect(
+        componentPreview.queryByLabelText('Receives confirmation email')
+      ).not.toBeInTheDocument();
     });
 
     await step('Submit form', async () => {
+      // Reselect the email address type
+      const typeSelect = componentEditForm.getByText((_, element) => {
+        return element?.id === 'editform-digitalAddressTypes';
+      });
```
Comment (sergei-maertens) [inline src/components/ComponentConfiguration.stories.tsx]: is there no accessible query how you can do this? We do have some utilities that wrap around https://www.npmjs.com/package/react-select-event afaik

**Review by sergei-maertens — APPROVED** [review]
